name: RGBArmor
version: 0.0.1
author: tryy3
main: us.tryy3.rgbarmor.Main
commands:
  rgbarmor:
    description: Awesome leather armor.
    aliases: [rgb, armor, rainbow, leather]
    usage: /<command> [help [command]|toggle|rainbow [animation]]